build:
    environment:
        variables:
            MONGO_TEST_DB: '1'
    tests:
        override:
            -
                command: 'npm run test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - "__tests__"
        - "__mocks__"
        - "coverage"
        - "dist/*"
        - "docker"
        - "node_modules"

checks:
    javascript:
        code_rating: true
        duplicate_code: true
